[workspace]
resolver = "3"
members = ["bindings"]

[workspace.package]
keywords = ["anoma", "evm", "protocol-adapter", "erc20", "forwarder"]
authors = ["Anoma Foundation"]
license = "MIT"
repository = "https://github.com/anoma/anomapay-erc20-forwarder"
homepage = "https://anomapay.app/"
edition = "2024"

[workspace.dependencies]
alloy = { version = "1.4.0", features = ["full", "eip712", "node-bindings"] }
alloy-chains = "0.2.27"
anoma-rm-risc0 = { version = "1.0.0", features = ["bonsai", "aggregation"] }
anoma-rm-risc0-test-app = { version = "1.0.0", features = ["bonsai"] }
dotenvy = { version = "0.15.7" }
serde = { version = "1.0.228", default-features = false }
thiserror = "2.0.17"
tokio = { version = "1.49", features = ["rt-multi-thread"] }
anoma-pa-evm-bindings = "1.0.0-rc.10"
anomapay-erc20-forwarder-bindings = { path = "bindings" }
