[workspace]
resolver = "2"

members = ["simple_transfer/transfer_app"]
exclude = ["native"]

# Always optimize; building and running the guest takes much longer without optimization.
[profile.dev]
opt-level = 3

[profile.release]
debug = 1
lto = true

[patch."https://github.com/anoma/arm-risc0"]
arm = { version = "0.8.1", path = "./target/patch/arm" }
