[workspace]
resolver = "2"
members = ["simple_transfer/transfer_app", "bindings"]

[workspace.package]
authors = ["Heliax <hello@heliax.dev>"]
edition = "2024"
license = "GPL-3.0"
readme = "README.md"
version = "0.0.1"

[workspace.dependencies]
alloy = { version = "1.1.0", features = ["full"] }
alloy-chains = "0.2.18"
tokio = { version = "1.48", features = ["rt-multi-thread"] }
serde = { version = "1.0" }
thiserror = "2.0.17"
dotenv = "0.15.0"
async-trait = "0.1.89"
bincode = "1.3.3"
chrono = "0.4.42"
futures = "0.3.31"
itertools = "0.14.0"
k256 = { version = "0.13", default-features = false }
log = "0.4.28"
rand = "0.9.2"
reqwest = "0.12"
risc0-zkvm = "3.0.3"
serde_json = "1.0"
serde_with = { version = "3.0", features = ["hex"] }
rocket = { version = "0.5", features = ["json"] }
typetag = "0.2.21"
utoipa = "5"
base64 = "0.22.1"
utoipa-swagger-ui = { version = "9", features = ["rocket"] }
enum_dispatch = "0.3"
strum = "0.27.2"
lazy_static = "1.5.0"
hex = "0.4"
alloy-primitives = "1.0.23"
alloy-sol-types = "1.0.23"

evm_protocol_adapter_bindings = { git = "https://github.com/anoma/evm-protocol-adapter", tag = "bindings/v1.0.0-rc.6" }
arm = { git = "https://github.com/anoma/arm-risc0", tag = "v0.13.0", default-features = false }
arm-gadgets = { git = "https://github.com/anoma/arm-risc0", tag = "v0.13.0" }

transfer_library = { path = "simple_transfer/transfer_library" }
transfer_witness = { path = "simple_transfer/transfer_witness" }

# Always optimize; building and running the guest takes much longer without optimization.
[profile.dev]
opt-level = 3
