services:
  api:
    build: .
    environment:
      - RPC_URL=${RPC_URL}
      - GALILEO_INDEXER_ADDRESS=${GALILEO_INDEXER_ADDRESS}
      - FEE_PAYMENT_WALLET_PRIVATE_KEY=${FEE_PAYMENT_WALLET_PRIVATE_KEY}
      - ALCHEMY_API_KEY=${ALCHEMY_API_KEY}
      - BONSAI_API_URL=${BONSAI_API_URL}
      - BONSAI_API_KEY=${BONSAI_API_KEY}
    ports:
      - "8000:8000"
