include = ["Cargo.toml", "simple_transfer/transfer_app/Cargo.toml", "simple_transfer/transfer_circuit/Cargo.toml", "simple_transfer/transfer_library/Cargo.toml", "simple_transfer/transfer_witness/Cargo.toml"]

[formatting]
reorder_keys = true