[package]
authors.workspace = true
edition.workspace = true
license.workspace = true
name = "token-transfer-methods"
readme.workspace = true
version.workspace = true

[build-dependencies]
risc0-build = { workspace = true, features = ["unstable"] }

[package.metadata.risc0]
methods = ["guest"]
