[package]
authors.workspace = true
edition.workspace = true
license.workspace = true
name = "transfer_library"
readme.workspace = true
version.workspace = true

[dependencies]
arm = { workspace = true, features = ["transaction"] }
arm-gadgets = { workspace = true }
hex = { workspace = true }
k256 = { workspace = true, features = [
  "arithmetic",
  "serde",
  "expose-field",
  "std",
  "ecdsa",
  "hash2curve",
], default-features = false }
lazy_static = { workspace = true }
serde = { workspace = true, features = ["derive"] }
transfer_witness = { workspace = true }
