[package]
name = "simple-transfer"
authors.workspace = true
edition.workspace = true
license.workspace = true
readme.workspace = true
version.workspace = true

[workspace]

[dependencies]
simple-transfer-methods = { path = "methods" }
risc0-zkvm = { workspace = true }
