[package]
authors.workspace = true
edition.workspace = true
license.workspace = true
name = "simple-transfer"
readme.workspace = true
version.workspace = true

[workspace]

[dependencies]
risc0-zkvm = { workspace = true }
simple-transfer-methods = { path = "methods" }
