[package]
name = "transfer_witness"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0"
arm = { git = "https://github.com/anoma/arm-risc0", tag = "v0.8.1", default-features = false }
rand = "0.8"
