[package]
name = "erc20_forwarder_bindings"
version = "1.0.0-rc.1"
edition = "2024"

[dependencies]
evm_protocol_adapter_bindings = { git = "https://github.com/anoma/evm-protocol-adapter", tag = "bindings/v1.0.0-rc.6" }
alloy = { version = "1.1.0", features = ["full", "eip712", "node-bindings"] }
alloy-chains = "0.2.18"
tokio = { version = "1.48", features = ["rt-multi-thread"] }
serde = { version = "1.0.228", default-features = false }
thiserror = "2.0.17"
dotenv = { version = "0.15.0", features = ["cli"] }
